# Generated by Django 2.1.5 on 2019-03-06 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_name', models.CharField(max_length=45)),
                ('apply_schoolNum', models.CharField(max_length=45)),
                ('apply_phone', models.CharField(max_length=45)),
                ('apply_department', models.CharField(max_length=45)),
                ('apply_location', models.CharField(max_length=45)),
                ('apply_email', models.CharField(max_length=45)),
                ('apply_question1', models.TextField()),
                ('apply_question2', models.TextField()),
                ('apply_question3', models.TextField()),
                ('apply_question4', models.TextField()),
                ('apply_question5', models.TextField()),
                ('apply_total', models.IntegerField(default=0)),
                ('apply_avg', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_point1', models.IntegerField(default=0)),
                ('apply_point2', models.IntegerField(default=0)),
                ('apply_point3', models.IntegerField(default=0)),
                ('apply_point4', models.IntegerField(default=0)),
                ('apply_point5', models.IntegerField(default=0)),
                ('apply_point_total', models.IntegerField(default=0)),
                ('apply_point_avg', models.FloatField(default=0)),
                ('apply_point_comment', models.TextField(max_length=200)),
                ('apply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apply.Apply')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
